CREATE TABLE TBL_TIPO_REGISTRO (
	CD_TIPO_REGISTRO INT UNIQUE NOT NULL IDENTITY(1,1)
	,CD_ORGAO INT
	,DS_TIPO_REGISTRO VARCHAR(100) NOT NULL
	,SG_TIPO_REGISTRO VARCHAR(5)UNIQUE NOT NULL
	,CONSTRAINT PK_TBL_TIPO_REGISTRO_CD_TIPO_REGISTRO PRIMARY KEY (CD_TIPO_REGISTRO)
);

CREATE TABLE TBL_ENTIDADES_ORGAO (
	CD_ORGAO INT UNIQUE NOT NULL IDENTITY(1,1)
	,DS_ORGAO VARCHAR(100) NOT NULL
	,SG_ORGAO VARCHAR(5) UNIQUE NOT NULL
	,CONSTRAINT PK_TBL_ENTIDADES_ORGAO_CD_ORGAO PRIMARY KEY (CD_ORGAO)
);

CREATE TABLE TBL_ENTIDADES_VALIDADE (
	CD_VALIDADE INT UNIQUE NOT NULL IDENTITY(1,1)
	,CD_ENTIDADE INT  NOT NULL
	,CD_TIPO_REGISTRO INT NOT NULL
	,DS_REGISTRO VARCHAR(25) UNIQUE NOT NULL
	,DT_VALIDADE DATE
	,CONSTRAINT PK_TBL_ENTIDADES_VALIDADE_CD_VALIDADE PRIMARY KEY (CD_VALIDADE)
);

ALTER TABLE TBL_TIPO_REGISTRO
	ADD CONSTRAINT FK_TBL_TIPO_REGISTRO_CD_ORGAO 
	FOREIGN KEY (CD_ORGAO) 
	REFERENCES TBL_ENTIDADES_ORGAO(CD_ORGAO)
;

ALTER TABLE TBL_ENTIDADES_VALIDADE
	ADD CONSTRAINT FK_TBL_ENTIDADES_VALIDADE_CD_ENTIDADE 
	FOREIGN KEY (CD_ENTIDADE) 
	REFERENCES TBL_ENTIDADES(CD_ENTIDADE)
;

ALTER TABLE TBL_ENTIDADES_VALIDADE	
	ADD CONSTRAINT FK_TBL_ENTIDADES_VALIDADE_CD_TIPO_REGISTRO 
	FOREIGN KEY (CD_TIPO_REGISTRO) 
	REFERENCES TBL_TIPO_REGISTRO(CD_TIPO_REGISTRO)
;

INSERT INTO TBL_ENTIDADES_ORGAO (DS_ORGAO, SG_ORGAO)
VALUES 
	('EXÉRCITO BRASILEIRO', 'EX'),
	('POLÍCIA FEDERAL', 'PF'),
	('POLÍCIA CIVIL', 'PC')
;

INSERT INTO TBL_TIPO_REGISTRO (CD_ORGAO, DS_TIPO_REGISTRO, SG_TIPO_REGISTRO)
VALUES 
	(1,'TÍTULO DE REGISTRO', 'TR'), 
	(1,'CERTIFICADO DE REGISTRO', 'CR'), 
	(2,'CERTIFICADO DE REGISTRO CADASTRAL', 'CRC'), 
	(2,'CERTIFICADO DE LICENÇA DE FUNCIONAMENTO', 'CLF'),
	(3,'COMÉRCIO', 'COM'),
	(3,'IMPORTAÇÃO', 'IMP'),
	(3,'EXPORTAÇÃO', 'EXP'),
	(3,'TRANSPORTE', 'TRS'),
	(3,'DEPOSITO E ARMAZENAGEM', 'DEP'),
	(3,'VEICULO', 'VEI'),
	(3,'MOTORISTA', 'MOT')
;

GO
	DELETE FROM TBL_ENTIDADES_VALIDADE;

	DBCC CHECKIDENT('TBL_ENTIDADES_VALIDADE', RESEED, 0);

	INSERT INTO TBL_ENTIDADES_VALIDADE (CD_ENTIDADE, CD_TIPO_REGISTRO, DS_REGISTRO, DT_VALIDADE)
		SELECT TBLE.CD_ENTIDADE,
		CASE 
			SUBSTRING(TBLEC.DS_COMENTARIO, CHARINDEX('#',TBLEC.DS_COMENTARIO)-3,3)
			WHEN 'TR' THEN 1
			WHEN 'CR' THEN 2
			WHEN 'CRC' THEN 3
			WHEN 'CLF' THEN 4 
			WHEN 'COM' THEN 5
			WHEN 'IMP' THEN 6
			WHEN 'EXP' THEN 7
			WHEN 'TRS' THEN 8
			WHEN 'DEP' THEN 9
			WHEN 'VEI' THEN 10
			WHEN 'MOT' THEN 11
		END AS CD_TIPO_REGISTRO,
		REPLACE(
			CONCAT(
				SUBSTRING(TBLEC.DS_COMENTARIO, CHARINDEX('-',TBLEC.DS_COMENTARIO)-9,9),'-',
				SUBSTRING(TBLEC.DS_COMENTARIO, CHARINDEX('-',TBLEC.DS_COMENTARIO)+1,1)), '*', '') AS DS_REGISTRO,
		CAST(SUBSTRING(TBLEC.DS_COMENTARIO, CHARINDEX('D-', TBLEC.DS_COMENTARIO)+2,10) AS DATE) AS DT_VALIDADE
		FROM TBL_ENTIDADES TBLE
		JOIN TBL_ENTIDADES_COMENTARIOS TBLEC ON TBLE.CD_ENTIDADE = TBLEC.CD_ENTIDADE
		WHERE TBLEC.DS_COMENTARIO IN 
			(SELECT DS_COMENTARIO 
			FROM TBL_ENTIDADES_COMENTARIOS 
			WHERE  DS_COMENTARIO LIKE '%#%' AND DS_COMENTARIO IS NOT NULL);
GO

GO
	CREATE VIEW SEL_ENTIDADES_VALIDADE AS
		SELECT  TBLEV.CD_VALIDADE AS 'CÓD. VALIDADE', 
			TBLEV.CD_ENTIDADE AS 'CÓD. ENTIDADE', 
			TBLE.DS_ENTIDADE AS 'ENTIDADE', 
			TBLEO.DS_ORGAO AS 'ORGÃO', 
			TBLTR.DS_TIPO_REGISTRO 'DESCRIÇÃO DO REGISTRO', 
			TBLEV.DS_REGISTRO 'CÓD. REGISTRO',
			TBLEV.DT_VALIDADE
		FROM TBL_ENTIDADES_VALIDADE TBLEV
		JOIN TBL_ENTIDADES TBLE ON TBLE.CD_ENTIDADE = TBLEV.CD_ENTIDADE
		JOIN TBL_TIPO_REGISTRO TBLTR ON TBLEV.CD_TIPO_REGISTRO = TBLTR.CD_TIPO_REGISTRO
		JOIN TBL_ENTIDADES_ORGAO TBLEO ON TBLEO.CD_ORGAO = TBLTR.CD_ORGAO;
GO

SELECT * FROM SEL_ENTIDADES_VALIDADE;

TR#*12345678-0 D-10/10/10